#!/bin/bash

# flatten - Flatten directory structure by renaming files with their relative path

if [[ "$PWD" == "/" ]]; then
    echo "ERROR: Running this script in root (/) is not allowed."
    exit 1
fi

find . -type f | while read -r file; do
    new_name="${file:2}"
    new_name="${new_name//\//⧸}"
    mv "$file" "$new_name"
done


rm -rf ./*/


echo "Compression complete!"
