#!/bin/zsh

# Initialize an associative array to store the data
declare -A resource_data
declare -A key_list

# Read input line by line
while read -r line; do
    # Split the line into fields
    key=$(echo "$line" | awk '{print $1}')
    resource_id=$(echo "$line" | awk '{print $2}')
    type=$(echo "$line" | awk '{print $3}')
    value=$(echo "$line" | awk '{print $NF}')

    # Store the resource type for the resource ID
    resource_data[$resource_id,"Resource Type"]=$type

    # Store the value for the key and resource ID
    resource_data[$resource_id,$key]=$value
    key_list[$key]=1
done

# Extract unique resource_ids
unique_resource_ids=("${(@u)${(k)resource_data##*,}}")

# Print the header
printf "Resource Id\tResource Type\t"
for key in ${(k)key_list}; do
    printf "%s\t" "$key"
done
echo ""

# Print the data
for resource_id in $unique_resource_ids; do
    printf "%s\t%s\t" "$resource_id" "${resource_data[$resource_id,'Resource Type']}"
    for key in ${(k)key_list}; do
        if [[ -n "${resource_data[$resource_id,$key]}" ]]; then
            printf "%s\t" "${resource_data[$resource_id,$key]}"
        else
            printf "N/A\t"
        fi
    done
    echo ""
done
