#!/bin/zsh

# Initialize an associative array to store the data
declare -A data

# Read input line by line
while read -r line; do
    # Split the line into fields
    key=$(echo "$line" | awk '{print $1}')
    resource_id=$(echo "$line" | awk '{print $2}')
    type=$(echo "$line" | awk '{print $3}')
    value=$(echo "$line" | awk '{print $NF}')

    # Store the value in the associative array with the resource_id and key as keys
    data[$resource_id,$key]=$value
done

# Extract unique resource_ids
unique_resource_ids=("${(@u)${(k)data##*,}}")

# Print the header
printf "Resource Id\t"
for key in ${(k)data##*,}; do
    printf "%s\t" "$key"
done
echo ""

# Print the data
for resource_id in $unique_resource_ids; do
    printf "%s\t" "$resource_id"
    for key in ${(k)data##*,}; do
        if [[ -n "${data[$resource_id,$key]}" ]]; then
            printf "%s\t" "${data[$resource_id,$key]}"
        else
            printf "N/A\t"
        fi
    done
    echo ""
done
