#!/bin/bash

# unflatten - Restore directory structure from flattened filenames

if [[ "$PWD" == "/" ]]; then
    echo "ERROR: Running this script in root (/) is not allowed."
    exit 1
fi

list_all_files() {
    find . -type f
    find . -type f -empty
}

 list_all_files | while read -r file; do
    new_path="${file//⧸/\/}"  # Replace ⧸ with /
    
    if [[ "$new_path" == "$file" ]]; then
        # Skipping file (No ⧸ found)
        continue
    fi

    dir_name="$(dirname "$new_path")"
    mkdir -p "$($dir_name | sed 's/\\//g')"
    mv "$file" "$($new_path | sed 's/\\//g')"
done

echo "Expansion complete!"
